(define (make-interval a b) (cons a b))

(define (upper-bound i)
  (cdr i))

(define (lower-bound i)
  (car i))

(define (mul-interval x y)
  (let ((p1 (* (lower-bound x) (lower-bound y)))
        (p2 (* (lower-bound x) (upper-bound y)))
        (p3 (* (upper-bound x) (lower-bound y)))
        (p4 (* (upper-bound x) (upper-bound y))))
    (make-interval (min p1 p2 p3 p4)
                   (max p1 p2 p3 p4))))

(define (mul-interval x y)
  (let ((xl (lower-bound x))
        (xu (upper-bound x))
        (yl (lower-bound y))
        (yu (upper-bound y)))
    (define (n? x) (< x 0))
    (define (p? x) (>= x 0))
    (define (signs x y)
      (cond ((and (n? xl) (n? xu) (n? yl) (n? yu)) "----")
            ((and (n? xl) (n? xu) (n? yl) (p? yu)) "---+")
            ((and (n? xl) (n? xu) (p? yl) (p? yu)) "--++")
            ((and (n? xl) (p? xu) (n? yl) (n? yu)) "-+--")
            ((and (n? xl) (p? xu) (n? yl) (p? yu)) "-+-+")
            ((and (n? xl) (p? xu) (p? yl) (p? yu)) "-+++")
            ((and (p? xl) (p? xu) (n? yl) (n? yu)) "++--")
            ((and (p? xl) (p? xu) (n? yl) (p? yu)) "++-+")
            ((and (p? xl) (p? xu) (p? yl) (p? yu)) "++++")))
    (cond ((equal? "----" (signs x y))
           (make-interval (* xu yu) (* xl yl)))
          ((equal? "---+" (signs x y))
           (make-interval (* xl yu) (* xl yl)))
          ((equal? "--++" (signs x y))
           (make-interval (* xl yu) (* xu yl)))
          ((equal? "-+--" (signs x y))
           (make-interval (* xu yl) (* xl yl)))
          ((equal? "-+-+" (signs x y))
           (let ((p1 (* xl yl))
                 (p2 (* xl yu))
                 (p3 (* xu yl))
                 (p4 (* xu yu)))
             (make-interval (min p1 p2 p3 p4)
                            (max p1 p2 p3 p4))))
          ((equal? "-+++" (signs x y))
           (make-interval (* xl yu) (* xu yu)))
          ((equal? "++--" (signs x y))
           (make-interval (* xu yl) (* xl yu)))
          ((equal? "++-+" (signs x y))
           (make-interval (* xu yl) (xu yu)))
          ((equal? "++++" (signs x y))
           (make-interval (* xl yl) (* xu yu))))))

(mul-interval (make-interval 2 4)
              (make-interval -2 -4))
